# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Nema
tagline:             'A loose thread of my travels'
description:         ''
url:                 http://compor.github.io
baseurl:             ''
gems:                [jekyll-paginate, jekyll-feed]
paginate:            5
paginate_path:       "page:num"
include:            ["_pages"]
permalink:          /:title/

# About/contact
author:
  name:              Chris Vasiladiotis
  url:               https://twitter.com/compor
  email:             cvassiladiotis@gmail.com

# Custom vars
version:             1.0.0
